-- =====================================================================
-- V1__baseline.sql   AI Interview Platform — Phase 0 baseline schema
--
-- 18 tables. Creation order respects FK dependencies.
-- Source of truth: docs/10-architecture-review.md (approved).
--
-- Ids are UUIDv7 generated by the application (IdGenerator). The
-- gen_random_uuid() DEFAULT is a safety net for manual/seed inserts only.
--
-- Deviations from the approved DDL text are marked [FIX-n] and are
-- documented in docs/m0-m1-implementation.md § Problems discovered.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS app;
CREATE EXTENSION IF NOT EXISTS pgcrypto;   -- gen_random_uuid() fallback

-- ---------------------------------------------------------------- utility
CREATE FUNCTION app.touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END $$;

-- Documented escape hatch for data-repair migrations only:
--   SET LOCAL app.allow_immutable_write = 'on';
CREATE FUNCTION app.immutable_bypass() RETURNS boolean LANGUAGE sql STABLE AS $$
  SELECT coalesce(current_setting('app.allow_immutable_write', true), 'off') = 'on'
$$;

-- ============================================================ 1. skills
CREATE TABLE app.skills (
    id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    code        text        NOT NULL,
    name        text        NOT NULL,
    description text        NULL,
    status      text        NOT NULL DEFAULT 'ACTIVE',
    sort_order  smallint    NOT NULL DEFAULT 100,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_skills_code   UNIQUE (code),
    CONSTRAINT ck_skills_status CHECK (status IN ('ACTIVE','ARCHIVED'))
);

-- ============================================================= 2. users
-- [FIX-2] email is `text` with a functional unique index on lower(email)
-- instead of `citext`. citext is reported as Types.OTHER by the pgjdbc
-- driver, which makes Hibernate `ddl-auto=validate` fail against a String
-- field. The invariant (case-insensitive uniqueness) is identical.
CREATE TABLE app.users (
    id                uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    auth_subject      text        NOT NULL,          -- opaque IdP 'sub'; NOT a FK
    auth_provider     text        NOT NULL DEFAULT 'supabase',
    email             text        NOT NULL,
    email_verified    boolean     NOT NULL DEFAULT false,
    display_name      text        NULL,
    role              text        NOT NULL DEFAULT 'CANDIDATE',
    status            text        NOT NULL DEFAULT 'ACTIVE',
    role_changed_at   timestamptz NULL,
    role_changed_by   uuid        NULL,
    status_changed_at timestamptz NULL,
    status_changed_by uuid        NULL,
    last_seen_at      timestamptz NULL,
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_users_auth   UNIQUE (auth_provider, auth_subject),
    CONSTRAINT ck_users_role   CHECK (role   IN ('CANDIDATE','ADMIN')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE','SUSPENDED','DELETED')),
    CONSTRAINT fk_users_role_by   FOREIGN KEY (role_changed_by)
        REFERENCES app.users(id) ON DELETE SET NULL,
    CONSTRAINT fk_users_status_by FOREIGN KEY (status_changed_by)
        REFERENCES app.users(id) ON DELETE SET NULL
);
CREATE UNIQUE INDEX uq_users_email ON app.users (lower(email));

-- ========================================================== 3. profiles
CREATE TABLE app.profiles (
    user_id          uuid        PRIMARY KEY
                                 REFERENCES app.users(id) ON DELETE CASCADE,
    full_name        text        NULL,
    headline         text        NULL,
    years_experience smallint    NULL,
    target_role      text        NULL,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_profiles_years CHECK (years_experience IS NULL
                                        OR years_experience BETWEEN 0 AND 50)
);

-- ========================================================= 4. questions
-- Stable identity of a question across content revisions.
CREATE TABLE app.questions (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    question_key text        NOT NULL,   -- 'java.hashmap-vs-chm'; seeding idempotency
    status       text        NOT NULL DEFAULT 'ACTIVE',
    created_by   uuid        NULL REFERENCES app.users(id) ON DELETE SET NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_questions_key    UNIQUE (question_key),
    CONSTRAINT ck_questions_status CHECK (status IN ('ACTIVE','ARCHIVED'))
);

-- ================================================= 5. question_versions
-- IMMUTABLE once PUBLISHED. The foundation of score comparability.
CREATE TABLE app.question_versions (
    id                    uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    question_id           uuid        NOT NULL
                          REFERENCES app.questions(id) ON DELETE CASCADE,
    version               integer     NOT NULL,
    skill_id              uuid        NOT NULL
                          REFERENCES app.skills(id) ON DELETE RESTRICT,
    question_type         text        NOT NULL DEFAULT 'CONCEPTUAL',
    difficulty            text        NOT NULL,
    prompt_text           text        NOT NULL,
    context_text          text        NULL,
    reference_answer      text        NULL,   -- required to publish (trigger)
    expected_duration_sec integer     NOT NULL DEFAULT 120,
    status                text        NOT NULL DEFAULT 'DRAFT',
    published_at          timestamptz NULL,
    published_by          uuid        NULL REFERENCES app.users(id) ON DELETE SET NULL,
    archived_at           timestamptz NULL,
    archived_by           uuid        NULL REFERENCES app.users(id) ON DELETE SET NULL,
    created_by            uuid        NULL REFERENCES app.users(id) ON DELETE SET NULL,
    created_at            timestamptz NOT NULL DEFAULT now(),
    updated_at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_qv_question_version UNIQUE (question_id, version),
    CONSTRAINT ck_qv_version    CHECK (version >= 1),
    CONSTRAINT ck_qv_type       CHECK (question_type IN
                                ('CONCEPTUAL','SCENARIO','DESIGN','TROUBLESHOOTING')),
    CONSTRAINT ck_qv_difficulty CHECK (difficulty IN ('EASY','MEDIUM','HARD')),
    CONSTRAINT ck_qv_status     CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED')),
    CONSTRAINT ck_qv_prompt_len CHECK (length(prompt_text) BETWEEN 10 AND 4000),
    CONSTRAINT ck_qv_duration   CHECK (expected_duration_sec BETWEEN 30 AND 900),
    CONSTRAINT ck_qv_published  CHECK (status = 'DRAFT'
                                OR (published_at IS NOT NULL AND reference_answer IS NOT NULL))
);
CREATE UNIQUE INDEX uq_qv_one_published ON app.question_versions(question_id)
  WHERE status = 'PUBLISHED';
CREATE INDEX ix_qv_pool ON app.question_versions(skill_id, difficulty)
  WHERE status = 'PUBLISHED';

-- ==================================================== 6. rubric_criteria
-- The rubric, versioned WITH the question version: a rubric change IS a
-- content change. Weights must sum to 10000 bp at publish time.
CREATE TABLE app.rubric_criteria (
    id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    question_version_id uuid        NOT NULL
                        REFERENCES app.question_versions(id) ON DELETE CASCADE,
    code                text        NOT NULL,   -- 'THREAD_SAFETY'
    label               text        NOT NULL,   -- candidate-facing
    expectation         text        NOT NULL,   -- observable claim, for the grader
    weight_bp           integer     NOT NULL,
    tier                text        NOT NULL DEFAULT 'CORE',
    follow_up_prompt    text        NULL,       -- absorbed from follow_up_prompts
    sort_order          smallint    NOT NULL DEFAULT 100,
    created_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_rc_code   UNIQUE (question_version_id, code),
    CONSTRAINT ck_rc_weight CHECK (weight_bp > 0 AND weight_bp <= 10000),
    CONSTRAINT ck_rc_tier   CHECK (tier IN ('CORE','DEPTH','BONUS'))
);

-- ================================================ 7. interview_templates
-- IMMUTABLE once PUBLISHED.
CREATE TABLE app.interview_templates (
    id                        uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    template_key              text        NOT NULL,
    version                   integer     NOT NULL,
    title                     text        NOT NULL,
    summary                   text        NULL,
    description               text        NULL,
    instructions              text        NULL,
    level                     text        NOT NULL DEFAULT 'MID',
    status                    text        NOT NULL DEFAULT 'DRAFT',
    core_question_count       smallint    NOT NULL DEFAULT 8,
    max_follow_ups_total      smallint    NOT NULL DEFAULT 4,
    max_follow_ups_per_parent smallint    NOT NULL DEFAULT 2,
    target_duration_min       smallint    NOT NULL DEFAULT 18,
    hard_duration_min         smallint    NOT NULL DEFAULT 45,
    published_at              timestamptz NULL,
    published_by              uuid        NULL REFERENCES app.users(id) ON DELETE SET NULL,
    archived_at               timestamptz NULL,
    archived_by               uuid        NULL REFERENCES app.users(id) ON DELETE SET NULL,
    created_by                uuid        NULL REFERENCES app.users(id) ON DELETE SET NULL,
    created_at                timestamptz NOT NULL DEFAULT now(),
    updated_at                timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_tpl_key_version UNIQUE (template_key, version),
    CONSTRAINT ck_tpl_version   CHECK (version >= 1),
    CONSTRAINT ck_tpl_level     CHECK (level  IN ('ENTRY','JUNIOR','MID','SENIOR')),
    CONSTRAINT ck_tpl_status    CHECK (status IN ('DRAFT','PUBLISHED','ARCHIVED')),
    CONSTRAINT ck_tpl_counts    CHECK (core_question_count BETWEEN 3 AND 20
                                   AND max_follow_ups_total BETWEEN 0 AND 10
                                   AND max_follow_ups_per_parent BETWEEN 0 AND 3),
    CONSTRAINT ck_tpl_durations CHECK (target_duration_min BETWEEN 5 AND 120
                                   AND hard_duration_min >= target_duration_min),
    CONSTRAINT ck_tpl_published CHECK (status = 'DRAFT' OR published_at IS NOT NULL)
);
CREATE UNIQUE INDEX uq_tpl_one_published ON app.interview_templates(template_key)
  WHERE status = 'PUBLISHED';

-- ==================================================== 8. template_skills
CREATE TABLE app.template_skills (
    template_id uuid    NOT NULL
                REFERENCES app.interview_templates(id) ON DELETE CASCADE,
    skill_id    uuid    NOT NULL REFERENCES app.skills(id) ON DELETE RESTRICT,
    weight_bp   integer NOT NULL,
    CONSTRAINT pk_template_skills PRIMARY KEY (template_id, skill_id),
    CONSTRAINT ck_ts_weight CHECK (weight_bp > 0 AND weight_bp <= 10000)
);

-- ============================================ 9. template_question_slots
-- One ordered row per core question. question_id XOR skill_id.
CREATE TABLE app.template_question_slots (
    id            uuid     PRIMARY KEY DEFAULT gen_random_uuid(),
    template_id   uuid     NOT NULL
                  REFERENCES app.interview_templates(id) ON DELETE CASCADE,
    position      smallint NOT NULL,
    question_id   uuid     NULL REFERENCES app.questions(id) ON DELETE RESTRICT,
    skill_id      uuid     NULL REFERENCES app.skills(id)    ON DELETE RESTRICT,
    difficulty    text     NULL,
    question_type text     NULL,
    weight_bp     integer  NOT NULL,
    CONSTRAINT uq_tqs_position UNIQUE (template_id, position),
    CONSTRAINT ck_tqs_position CHECK (position >= 1),
    CONSTRAINT ck_tqs_weight   CHECK (weight_bp > 0),
    CONSTRAINT ck_tqs_mode     CHECK (num_nonnulls(question_id, skill_id) = 1),
    CONSTRAINT ck_tqs_diff     CHECK (difficulty IS NULL
                                      OR difficulty IN ('EASY','MEDIUM','HARD')),
    CONSTRAINT ck_tqs_type     CHECK (question_type IS NULL OR question_type IN
                                ('CONCEPTUAL','SCENARIO','DESIGN','TROUBLESHOOTING'))
);

-- ======================================================== 10. interviews
-- One candidate attempt. RESTRICT on both parents: neither the candidate
-- nor the pinned template version can be deleted while this exists.
--
-- [FIX-3] ck_int_terminal was split. The approved single constraint tied
-- completion_reason to the terminal states, but every transition INTO
-- COMPLETING already carries its reason (CANDIDATE_FINISHED, TIME_EXPIRED,
-- ALL_ANSWERED, AUTO_COMPLETED). The original form made it impossible to
-- record the reason at the moment it is known. Invariant #24 is preserved:
-- a terminal attempt still requires BOTH completed_at and completion_reason.
CREATE TABLE app.interviews (
    id                     uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    candidate_user_id      uuid        NOT NULL
                           REFERENCES app.users(id) ON DELETE RESTRICT,
    template_id            uuid        NOT NULL
                           REFERENCES app.interview_templates(id) ON DELETE RESTRICT,
    status                 text        NOT NULL DEFAULT 'IN_PROGRESS',
    completion_reason      text        NULL,
    hard_deadline_at       timestamptz NOT NULL,
    last_activity_at       timestamptz NOT NULL DEFAULT now(),
    follow_ups_selected_at timestamptz NULL,  -- NULL = selector has not run
    completing_at          timestamptz NULL,  -- drives the 15-minute ceiling
    completed_at           timestamptz NULL,
    completed_by           uuid        NULL REFERENCES app.users(id) ON DELETE SET NULL,
    engine_version         text        NOT NULL,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_int_status CHECK (status IN
        ('IN_PROGRESS','COMPLETING','COMPLETED','ABANDONED')),
    CONSTRAINT ck_int_reason CHECK (completion_reason IS NULL OR completion_reason IN
        ('CANDIDATE_FINISHED','ALL_ANSWERED','TIME_EXPIRED','AUTO_COMPLETED',
         'ABANDONED_BY_CANDIDATE','ABANDONED_EXPIRED','ABANDONED_BY_ADMIN')),
    -- Terminal <=> completed_at present.
    CONSTRAINT ck_int_terminal CHECK (
        (status IN ('COMPLETED','ABANDONED')) = (completed_at IS NOT NULL)),
    -- Terminal states must carry a reason; IN_PROGRESS must not.
    CONSTRAINT ck_int_reason_when CHECK (
        (status = 'IN_PROGRESS' AND completion_reason IS NULL)
     OR (status = 'COMPLETING')
     OR (status IN ('COMPLETED','ABANDONED') AND completion_reason IS NOT NULL))
);
CREATE UNIQUE INDEX uq_interviews_one_live ON app.interviews(candidate_user_id)
  WHERE status IN ('IN_PROGRESS','COMPLETING');
CREATE INDEX ix_interviews_candidate ON app.interviews(candidate_user_id, created_at DESC);
CREATE INDEX ix_interviews_sweep     ON app.interviews(hard_deadline_at)
  WHERE status IN ('IN_PROGRESS','COMPLETING');

-- =============================================== 11. interview_questions
-- THE TURN. skill_id and weight_bp are deliberate snapshots so the score is
-- recomputable from attempt-scoped tables alone.
-- [FIX-1] `uq_iq_position` had a transcription artefact in the approved text.
CREATE TABLE app.interview_questions (
    id                     uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    interview_id           uuid        NOT NULL
                           REFERENCES app.interviews(id) ON DELETE CASCADE,
    position               integer     NOT NULL,
    kind                   text        NOT NULL,
    parent_id              uuid        NULL
                           REFERENCES app.interview_questions(id) ON DELETE CASCADE,
    question_version_id    uuid        NOT NULL
                           REFERENCES app.question_versions(id) ON DELETE RESTRICT,
    skill_id               uuid        NOT NULL
                           REFERENCES app.skills(id) ON DELETE RESTRICT,
    weight_bp              integer     NOT NULL,
    follow_up_criterion_id uuid        NULL
                           REFERENCES app.rubric_criteria(id) ON DELETE RESTRICT,
    prompt_text            text        NULL,   -- snapshot; follow-ups only
    status                 text        NOT NULL DEFAULT 'PENDING',
    asked_at               timestamptz NULL,
    time_spent_sec         integer     NULL,
    created_at             timestamptz NOT NULL DEFAULT now(),
    updated_at             timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT uq_iq_position UNIQUE (interview_id, position),
    CONSTRAINT ck_iq_position CHECK (position >= 1),
    CONSTRAINT ck_iq_kind     CHECK (kind IN ('CORE','FOLLOW_UP')),
    CONSTRAINT ck_iq_status   CHECK (status IN
        ('PENDING','ASKED','ANSWERED','SKIPPED','EVALUATED','EVAL_FAILED')),
    CONSTRAINT ck_iq_time     CHECK (time_spent_sec IS NULL OR time_spent_sec >= 0),
    -- Core turns carry weight and no parent; follow-ups carry a parent, a
    -- targeted criterion, their own prompt text, and ZERO weight.
    CONSTRAINT ck_iq_shape CHECK (
        (kind = 'CORE'      AND parent_id IS NULL     AND weight_bp > 0
                            AND follow_up_criterion_id IS NULL AND prompt_text IS NULL)
     OR (kind = 'FOLLOW_UP' AND parent_id IS NOT NULL AND weight_bp = 0
                            AND follow_up_criterion_id IS NOT NULL AND prompt_text IS NOT NULL)),
    CONSTRAINT ck_iq_asked CHECK (status = 'PENDING' OR asked_at IS NOT NULL)
);

-- =========================================================== 12. answers
-- PK = the turn. This single constraint IS the answer-idempotency story.
-- content_text is immutable (trigger). Skipped turns create NO row here.
CREATE TABLE app.answers (
    interview_question_id uuid        PRIMARY KEY
                          REFERENCES app.interview_questions(id) ON DELETE CASCADE,
    content_text          text        NOT NULL,
    input_mode            text        NOT NULL DEFAULT 'TEXT',
    submitted_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_answers_mode CHECK (input_mode IN ('TEXT','VOICE')),
    CONSTRAINT ck_answers_len  CHECK (length(content_text) BETWEEN 1 AND 4000)
);

-- ==================================================== 13. ai_invocations
CREATE TABLE app.ai_invocations (
    id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    purpose             text        NOT NULL,
    provider            text        NOT NULL,
    model               text        NOT NULL,   -- exact pinned id, never an alias
    prompt_version      text        NOT NULL,
    request_fingerprint text        NOT NULL,   -- sha256(prompt+model+inputs)
    status              text        NOT NULL,
    http_status         smallint    NULL,
    latency_ms          integer     NULL,
    input_tokens        integer     NULL,
    output_tokens       integer     NULL,
    cost_micros         bigint      NULL,       -- integer micro-USD, never float
    retry_index         smallint    NOT NULL DEFAULT 0,
    raw_response        jsonb       NULL,       -- purged at 30 days (answer text)
    error_detail        text        NULL,
    interview_id        uuid        NULL
                        REFERENCES app.interviews(id) ON DELETE SET NULL,
    answer_id           uuid        NULL
                        REFERENCES app.answers(interview_question_id) ON DELETE SET NULL,
    user_id             uuid        NULL REFERENCES app.users(id) ON DELETE SET NULL,
    trace_id            text        NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_ai_purpose CHECK (purpose IN ('ANSWER_EVALUATION','REPORT_SUMMARY')),
    CONSTRAINT ck_ai_status  CHECK (status IN
        ('SUCCEEDED','TIMEOUT','PROVIDER_ERROR','RATE_LIMITED','INVALID_OUTPUT')),
    CONSTRAINT ck_ai_cost    CHECK (cost_micros IS NULL OR cost_micros >= 0)
);
CREATE INDEX ix_ai_interview ON app.ai_invocations(interview_id);
CREATE INDEX ix_ai_user_day  ON app.ai_invocations(user_id, created_at DESC);
CREATE INDEX ix_ai_created   ON app.ai_invocations(created_at DESC);

-- ======================================================= 14. evaluations
-- Append-only. Written ONLY on a terminal outcome. Only is_current mutable.
CREATE TABLE app.evaluations (
    id                            uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    answer_id                     uuid         NOT NULL
                                  REFERENCES app.answers(interview_question_id) ON DELETE CASCADE,
    is_current                    boolean      NOT NULL DEFAULT true,
    status                        text         NOT NULL,
    derived_score                 numeric(4,2) NULL,  -- COMPUTED BY THE BACKEND
    model_reported_score          numeric(4,2) NULL,  -- divergence signal ONLY
    confidence                    numeric(4,3) NULL,
    summary                       text         NULL,
    follow_up_needed              boolean      NOT NULL DEFAULT false,
    follow_up_reason              text         NULL,
    follow_up_target_criterion_id uuid         NULL
                                  REFERENCES app.rubric_criteria(id) ON DELETE RESTRICT,
    injection_suspected           boolean      NOT NULL DEFAULT false,
    answer_off_topic              boolean      NOT NULL DEFAULT false,
    -- REPRODUCIBILITY PROVENANCE
    evaluation_version            text         NOT NULL,  -- credit table + algorithm
    prompt_version                text         NOT NULL,
    rubric_version                integer      NOT NULL,  -- question_versions.version
    question_version_id           uuid         NOT NULL
                                  REFERENCES app.question_versions(id) ON DELETE RESTRICT,
    provider                      text         NULL,      -- survives raw_response purge
    model                         text         NULL,
    ai_invocation_id              uuid         NULL
                                  REFERENCES app.ai_invocations(id) ON DELETE SET NULL,
    triggered_by                  uuid         NULL
                                  REFERENCES app.users(id) ON DELETE SET NULL,
    error_code                    text         NULL,
    error_detail                  text         NULL,
    created_at                    timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_eval_status CHECK (status IN
        ('SUCCEEDED','FAILED_VALIDATION','FAILED_PROVIDER')),
    CONSTRAINT ck_eval_score  CHECK (derived_score IS NULL OR derived_score BETWEEN 0 AND 10),
    CONSTRAINT ck_eval_conf   CHECK (confidence    IS NULL OR confidence    BETWEEN 0 AND 1),
    CONSTRAINT ck_eval_ok     CHECK (status <> 'SUCCEEDED' OR derived_score IS NOT NULL)
);
CREATE UNIQUE INDEX uq_evaluations_one_current ON app.evaluations(answer_id)
  WHERE is_current;
CREATE INDEX ix_evaluations_answer ON app.evaluations(answer_id);

-- ==================================== 15. evaluation_criterion_results
-- IMMUTABLE. weight_bp and credit are snapshots: the arithmetic in a
-- historical report is reproducible from this row alone.
-- [FIX-4] ck_ecr_span now enforces null-symmetry of the evidence offsets.
CREATE TABLE app.evaluation_criterion_results (
    id                  uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    evaluation_id       uuid         NOT NULL
                        REFERENCES app.evaluations(id) ON DELETE CASCADE,
    rubric_criterion_id uuid         NOT NULL
                        REFERENCES app.rubric_criteria(id) ON DELETE RESTRICT,
    verdict             text         NOT NULL,
    credit              numeric(4,3) NOT NULL,  -- snapshot of the credit table
    weight_bp           integer      NOT NULL,  -- snapshot of rubric_criteria.weight_bp
    confidence          numeric(4,3) NULL,
    evidence_quote      text         NULL,      -- VERBATIM substring (gate G4)
    evidence_start      integer      NULL,      -- offsets computed by US
    evidence_end        integer      NULL,
    evidence_rejected   boolean      NOT NULL DEFAULT false,
    comment             text         NULL,
    CONSTRAINT uq_ecr UNIQUE (evaluation_id, rubric_criterion_id),
    CONSTRAINT ck_ecr_verdict CHECK (verdict IN
        ('MET','PARTIAL','MISSING','CONTRADICTED')),
    CONSTRAINT ck_ecr_credit  CHECK (credit BETWEEN -1 AND 1),
    CONSTRAINT ck_ecr_weight  CHECK (weight_bp > 0),
    CONSTRAINT ck_ecr_conf    CHECK (confidence IS NULL OR confidence BETWEEN 0 AND 1),
    CONSTRAINT ck_ecr_span    CHECK (
        (evidence_start IS NULL) = (evidence_end IS NULL)
        AND (evidence_start IS NULL OR evidence_end > evidence_start))
);
CREATE INDEX ix_ecr_criterion ON app.evaluation_criterion_results(rubric_criterion_id);

-- ================================================= 16. interview_reports
-- Append-only. NO ROW EXISTS when coverage is 0 -> the NOT_SCORED state.
CREATE TABLE app.interview_reports (
    id                    uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    interview_id          uuid         NOT NULL
                          REFERENCES app.interviews(id) ON DELETE CASCADE,
    is_current            boolean      NOT NULL DEFAULT true,
    overall_score         numeric(4,2) NOT NULL,
    band                  text         NOT NULL,
    evaluated_weight_bp   integer      NOT NULL,
    total_weight_bp       integer      NOT NULL,
    questions_answered    smallint     NOT NULL,
    questions_skipped     smallint     NOT NULL,
    questions_failed      smallint     NOT NULL,
    duration_sec          integer      NULL,
    summary               text         NOT NULL,
    strengths             jsonb        NOT NULL DEFAULT '[]'::jsonb,
    improvements          jsonb        NOT NULL DEFAULT '[]'::jsonb,
    study_recommendations jsonb        NOT NULL DEFAULT '[]'::jsonb,
    reporting_version     text         NOT NULL,
    generated_by          uuid         NULL REFERENCES app.users(id) ON DELETE SET NULL,
    generated_at          timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_rep_score    CHECK (overall_score BETWEEN 0 AND 10),
    CONSTRAINT ck_rep_band     CHECK (band IN
        ('NEEDS_WORK','DEVELOPING','SOLID','STRONG')),
    CONSTRAINT ck_rep_coverage CHECK (evaluated_weight_bp > 0
                               AND evaluated_weight_bp <= total_weight_bp),
    CONSTRAINT ck_rep_json     CHECK (jsonb_typeof(strengths) = 'array'
                               AND jsonb_typeof(improvements) = 'array'
                               AND jsonb_typeof(study_recommendations) = 'array')
);
CREATE UNIQUE INDEX uq_reports_one_current ON app.interview_reports(interview_id)
  WHERE is_current;
CREATE INDEX ix_reports_interview ON app.interview_reports(interview_id);

-- ============================================== 17. report_skill_scores
CREATE TABLE app.report_skill_scores (
    id             uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
    report_id      uuid         NOT NULL
                   REFERENCES app.interview_reports(id) ON DELETE CASCADE,
    skill_id       uuid         NOT NULL REFERENCES app.skills(id) ON DELETE RESTRICT,
    score          numeric(4,2) NOT NULL,
    weight_bp      integer      NOT NULL,  -- snapshot of template_skills.weight_bp
    question_count smallint     NOT NULL,
    coverage_bp    integer      NOT NULL,
    CONSTRAINT uq_rss UNIQUE (report_id, skill_id),
    CONSTRAINT ck_rss_score    CHECK (score BETWEEN 0 AND 10),
    CONSTRAINT ck_rss_weight   CHECK (weight_bp > 0),
    CONSTRAINT ck_rss_coverage CHECK (coverage_bp BETWEEN 0 AND 10000)
);
CREATE INDEX ix_rss_skill ON app.report_skill_scores(skill_id);

-- ============================================================== 18. jobs
-- Operational. NO foreign keys by design: job rows must never block domain
-- deletes, and payload shape varies by type.
CREATE TABLE app.jobs (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    job_type     text        NOT NULL,
    dedupe_key   text        NOT NULL,   -- 'EVALUATE_ANSWER:<turnId>'
    payload      jsonb       NOT NULL,
    status       text        NOT NULL DEFAULT 'QUEUED',
    priority     smallint    NOT NULL DEFAULT 100,
    attempts     smallint    NOT NULL DEFAULT 0,
    max_attempts smallint    NOT NULL DEFAULT 4,
    run_after    timestamptz NOT NULL DEFAULT now(),
    locked_by    text        NULL,
    locked_at    timestamptz NULL,
    last_error   text        NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_jobs_type   CHECK (job_type IN
        ('EVALUATE_ANSWER','GENERATE_REPORT','MAINTENANCE')),
    CONSTRAINT ck_jobs_status CHECK (status IN
        ('QUEUED','RUNNING','SUCCEEDED','FAILED','DEAD')),
    CONSTRAINT ck_jobs_att    CHECK (attempts >= 0 AND attempts <= max_attempts + 1),
    CONSTRAINT ck_jobs_lock   CHECK ((status = 'RUNNING') = (locked_by IS NOT NULL))
);
-- PARTIAL: dedupe among ACTIVE jobs only, so the same logical work can be
-- re-enqueued after completion (admin re-evaluation). A full UNIQUE here
-- would permanently block re-evaluation once the first job succeeded.
CREATE UNIQUE INDEX uq_jobs_active_dedupe ON app.jobs(dedupe_key)
  WHERE status IN ('QUEUED','RUNNING');
CREATE INDEX ix_jobs_claim ON app.jobs(priority, run_after) WHERE status = 'QUEUED';
CREATE INDEX ix_jobs_stale ON app.jobs(locked_at)           WHERE status = 'RUNNING';

-- =====================================================================
-- IMMUTABILITY AND PUBLISH-VALIDATION TRIGGERS
--
-- These are what make "historically reproducible" a DATABASE guarantee
-- rather than an application convention. All guards fire on UPDATE (or
-- INSERT for composition children) only, so FK cascades are unaffected.
--
-- [FIX-5] Trigger names carry a numeric ordinal. PostgreSQL fires BEFORE
-- ROW triggers in alphabetical order by name; relying on incidental
-- alphabetical order of descriptive names is fragile.
-- =====================================================================

CREATE FUNCTION app.guard_question_version() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF app.immutable_bypass() OR OLD.status = 'DRAFT' THEN RETURN NEW; END IF;
  IF OLD.status = 'PUBLISHED' THEN
    IF NEW.question_id           IS DISTINCT FROM OLD.question_id
    OR NEW.version               IS DISTINCT FROM OLD.version
    OR NEW.skill_id              IS DISTINCT FROM OLD.skill_id
    OR NEW.question_type         IS DISTINCT FROM OLD.question_type
    OR NEW.difficulty            IS DISTINCT FROM OLD.difficulty
    OR NEW.prompt_text           IS DISTINCT FROM OLD.prompt_text
    OR NEW.context_text          IS DISTINCT FROM OLD.context_text
    OR NEW.reference_answer      IS DISTINCT FROM OLD.reference_answer
    OR NEW.expected_duration_sec IS DISTINCT FROM OLD.expected_duration_sec THEN
      RAISE EXCEPTION 'Published question version % is immutable; create version %',
        OLD.id, OLD.version + 1 USING ERRCODE = 'restrict_violation';
    END IF;
    IF NEW.status NOT IN ('PUBLISHED','ARCHIVED') THEN
      RAISE EXCEPTION 'PUBLISHED may only transition to ARCHIVED'
        USING ERRCODE = 'restrict_violation';
    END IF;
  ELSIF OLD.status = 'ARCHIVED' AND NEW.status <> 'ARCHIVED' THEN
    RAISE EXCEPTION 'ARCHIVED question versions cannot be revived'
      USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION app.validate_question_publish() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE n int; total int;
BEGIN
  IF NEW.status = 'PUBLISHED' AND OLD.status IS DISTINCT FROM 'PUBLISHED' THEN
    SELECT count(*), coalesce(sum(weight_bp),0) INTO n, total
      FROM app.rubric_criteria WHERE question_version_id = NEW.id;
    IF n < 3 OR n > 10 THEN
      RAISE EXCEPTION 'A question needs 3-10 rubric criteria (has %)', n
        USING ERRCODE = 'check_violation';
    END IF;
    IF total <> 10000 THEN
      RAISE EXCEPTION 'Rubric criterion weights must sum to 10000 bp (got %)', total
        USING ERRCODE = 'check_violation';
    END IF;
    NEW.published_at := coalesce(NEW.published_at, now());
  END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION app.guard_interview_template() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF app.immutable_bypass() OR OLD.status = 'DRAFT' THEN RETURN NEW; END IF;
  IF OLD.status = 'PUBLISHED' THEN
    IF NEW.template_key              IS DISTINCT FROM OLD.template_key
    OR NEW.version                   IS DISTINCT FROM OLD.version
    OR NEW.core_question_count       IS DISTINCT FROM OLD.core_question_count
    OR NEW.max_follow_ups_total      IS DISTINCT FROM OLD.max_follow_ups_total
    OR NEW.max_follow_ups_per_parent IS DISTINCT FROM OLD.max_follow_ups_per_parent
    OR NEW.target_duration_min       IS DISTINCT FROM OLD.target_duration_min
    OR NEW.hard_duration_min         IS DISTINCT FROM OLD.hard_duration_min THEN
      RAISE EXCEPTION 'Published template % is immutable; create version %',
        OLD.id, OLD.version + 1 USING ERRCODE = 'restrict_violation';
    END IF;
    IF NEW.status NOT IN ('PUBLISHED','ARCHIVED') THEN
      RAISE EXCEPTION 'PUBLISHED may only transition to ARCHIVED'
        USING ERRCODE = 'restrict_violation';
    END IF;
  END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION app.validate_template_publish() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE sw int; slots int; maxpos int; orphan int;
BEGIN
  IF NEW.status = 'PUBLISHED' AND OLD.status IS DISTINCT FROM 'PUBLISHED' THEN
    SELECT coalesce(sum(weight_bp),0) INTO sw
      FROM app.template_skills WHERE template_id = NEW.id;
    IF sw <> 10000 THEN
      RAISE EXCEPTION 'Template skill weights must sum to 10000 bp (got %)', sw
        USING ERRCODE = 'check_violation';
    END IF;
    SELECT count(*), coalesce(max(position),0) INTO slots, maxpos
      FROM app.template_question_slots WHERE template_id = NEW.id;
    IF slots <> NEW.core_question_count THEN
      RAISE EXCEPTION 'Template needs exactly % slots (has %)',
        NEW.core_question_count, slots USING ERRCODE = 'check_violation';
    END IF;
    IF maxpos <> slots THEN
      RAISE EXCEPTION 'Slot positions must be contiguous 1..%', slots
        USING ERRCODE = 'check_violation';
    END IF;
    SELECT count(*) INTO orphan
      FROM app.template_question_slots s
     WHERE s.template_id = NEW.id AND s.skill_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM app.template_skills ts
                        WHERE ts.template_id = NEW.id AND ts.skill_id = s.skill_id);
    IF orphan > 0 THEN
      RAISE EXCEPTION '% slot(s) reference a skill with no template weight', orphan
        USING ERRCODE = 'check_violation';
    END IF;
    NEW.published_at := coalesce(NEW.published_at, now());
  END IF;
  RETURN NEW;
END $$;

-- Children of versioned content: writable only while the parent is DRAFT.
CREATE FUNCTION app.guard_rubric_criteria() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE st text;
BEGIN
  IF app.immutable_bypass() THEN RETURN NEW; END IF;
  SELECT status INTO st FROM app.question_versions WHERE id = NEW.question_version_id;
  IF st IS DISTINCT FROM 'DRAFT' THEN
    RAISE EXCEPTION 'Rubric criteria are immutable once the question version is %', st
      USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION app.guard_template_child() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE st text;
BEGIN
  IF app.immutable_bypass() THEN RETURN NEW; END IF;
  SELECT status INTO st FROM app.interview_templates WHERE id = NEW.template_id;
  IF st IS DISTINCT FROM 'DRAFT' THEN
    RAISE EXCEPTION 'Template composition is immutable once the template is %', st
      USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN NEW;
END $$;

-- Historical attempt records: only the is_current flag may ever change.
CREATE FUNCTION app.guard_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE a jsonb := to_jsonb(OLD); b jsonb := to_jsonb(NEW);
BEGIN
  IF app.immutable_bypass() THEN RETURN NEW; END IF;
  IF (a - 'is_current') IS DISTINCT FROM (b - 'is_current') THEN
    RAISE EXCEPTION '% rows are append-only; only is_current may change', TG_TABLE_NAME
      USING ERRCODE = 'restrict_violation';
  END IF;
  RETURN NEW;
END $$;

CREATE FUNCTION app.guard_immutable_row() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF app.immutable_bypass() THEN RETURN NEW; END IF;
  RAISE EXCEPTION '% rows are immutable once written', TG_TABLE_NAME
    USING ERRCODE = 'restrict_violation';
END $$;

-- ------------------------------------------------------------ attachment
CREATE TRIGGER trg_skills_90_touch BEFORE UPDATE ON app.skills
  FOR EACH ROW EXECUTE FUNCTION app.touch_updated_at();
CREATE TRIGGER trg_users_90_touch BEFORE UPDATE ON app.users
  FOR EACH ROW EXECUTE FUNCTION app.touch_updated_at();
CREATE TRIGGER trg_profiles_90_touch BEFORE UPDATE ON app.profiles
  FOR EACH ROW EXECUTE FUNCTION app.touch_updated_at();
CREATE TRIGGER trg_questions_90_touch BEFORE UPDATE ON app.questions
  FOR EACH ROW EXECUTE FUNCTION app.touch_updated_at();

CREATE TRIGGER trg_qv_10_validate BEFORE UPDATE ON app.question_versions
  FOR EACH ROW EXECUTE FUNCTION app.validate_question_publish();
CREATE TRIGGER trg_qv_20_guard BEFORE UPDATE ON app.question_versions
  FOR EACH ROW EXECUTE FUNCTION app.guard_question_version();
CREATE TRIGGER trg_qv_90_touch BEFORE UPDATE ON app.question_versions
  FOR EACH ROW EXECUTE FUNCTION app.touch_updated_at();

CREATE TRIGGER trg_tpl_10_validate BEFORE UPDATE ON app.interview_templates
  FOR EACH ROW EXECUTE FUNCTION app.validate_template_publish();
CREATE TRIGGER trg_tpl_20_guard BEFORE UPDATE ON app.interview_templates
  FOR EACH ROW EXECUTE FUNCTION app.guard_interview_template();
CREATE TRIGGER trg_tpl_90_touch BEFORE UPDATE ON app.interview_templates
  FOR EACH ROW EXECUTE FUNCTION app.touch_updated_at();

CREATE TRIGGER trg_rc_20_guard BEFORE INSERT OR UPDATE ON app.rubric_criteria
  FOR EACH ROW EXECUTE FUNCTION app.guard_rubric_criteria();
CREATE TRIGGER trg_ts_20_guard BEFORE INSERT OR UPDATE ON app.template_skills
  FOR EACH ROW EXECUTE FUNCTION app.guard_template_child();
CREATE TRIGGER trg_tqs_20_guard BEFORE INSERT OR UPDATE ON app.template_question_slots
  FOR EACH ROW EXECUTE FUNCTION app.guard_template_child();

CREATE TRIGGER trg_interviews_90_touch BEFORE UPDATE ON app.interviews
  FOR EACH ROW EXECUTE FUNCTION app.touch_updated_at();
CREATE TRIGGER trg_iq_90_touch BEFORE UPDATE ON app.interview_questions
  FOR EACH ROW EXECUTE FUNCTION app.touch_updated_at();
CREATE TRIGGER trg_jobs_90_touch BEFORE UPDATE ON app.jobs
  FOR EACH ROW EXECUTE FUNCTION app.touch_updated_at();

CREATE TRIGGER trg_answers_20_immutable BEFORE UPDATE ON app.answers
  FOR EACH ROW EXECUTE FUNCTION app.guard_immutable_row();
CREATE TRIGGER trg_ecr_20_immutable BEFORE UPDATE ON app.evaluation_criterion_results
  FOR EACH ROW EXECUTE FUNCTION app.guard_immutable_row();
CREATE TRIGGER trg_rss_20_immutable BEFORE UPDATE ON app.report_skill_scores
  FOR EACH ROW EXECUTE FUNCTION app.guard_immutable_row();
CREATE TRIGGER trg_eval_20_append_only BEFORE UPDATE ON app.evaluations
  FOR EACH ROW EXECUTE FUNCTION app.guard_append_only();
CREATE TRIGGER trg_report_20_append_only BEFORE UPDATE ON app.interview_reports
  FOR EACH ROW EXECUTE FUNCTION app.guard_append_only();
